### ISSUE TITLE
bugfix to work on Nano 33 HW

### ISSUE THREAD

**Issue by arotman** [RobTillaart/MS5611_SPI#6] opened 2022-12-13 18:08 UTC
There is a bug on line 76 of MS5611_SPI.cpp that prevents this library from working with Arduino Nano 33 BLE.
One can not call mySPI->end() before calling mySPI->begin(), as this crashes in the Arduino NANO library file SPI.cpp (dereferences a NULL pointer).

I commented out line 76 to fix the problem, and the library worked great with Arduino Nano 33 BLE sense.

    mySPI = &SPI;
    // mySPI->end();         // remove or comment out this line. Can not call end() before call begin()
    mySPI->begin();

**Comment by RobTillaart** [comment] 2022-12-13 18:44
Thank you for reposting this issue.
I will try to fix it tomorrow - are you able to test

As this might also happen with other platforms i need to add a null test or so.

**Comment by arotman** [comment] 2022-12-13 19:49
Hi,

Thanks for the quick response. 
I am able to test.

FYI, below is the excerpted code, and you see that for end() the library code does not check if (dev == NULL).
This Arduino mbed_nano code should be enhanced to check if (dev == NULL). Can we notify someone about fixing this code too?

Regards,
Alan

<Library/Arduino15/packages/arduino/hardware/mbed_nano/3.4.1/libraries/SPI/SPI.cpp 98,24          90%
void arduino::MbedSPI::begin() {
    if (dev == NULL) {
      dev = new mbed_spi;
      dev->obj = NULL;
    }
    if (dev->obj == NULL) {
      dev->obj = new mbed::SPI(_mosi, _miso, _sck);
    }
}

void arduino::MbedSPI::end() {
    if (dev->obj != NULL) {
        delete dev->obj;
    }
}

**Comment by RobTillaart** [comment] 2022-12-14 09:48
Good investigation!

From boards.txt 
**nano33ble.compiler.mbed.arch.define=-DARDUINO_ARCH_NRF52840**
So it is possible to patch specifically for the NANO33

The GitHub archive can be found here:
https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/SPI/SPI.cpp

I will file an issue.

**Comment by RobTillaart** [comment] 2022-12-14 09:57
Issue created:

https://github.com/arduino/ArduinoCore-mbed/issues/590

**Comment by RobTillaart** [comment] 2022-12-14 10:10
I propose **not** to patch the MS5611_SPI library as the cause is indeed in a deeper layer.
A simple patch is commend the line until  Arduino  fixes it.

(I better spend my time to create the PR for the MBED SPI lib)

**Comment by RobTillaart** [comment] 2022-12-14 10:58
Need to sign a legal agreement to provide the fix. 
I do not sign for open source, so I cancelled the PR.

**Comment by RobTillaart** [comment] 2022-12-17 09:14
@arotman 
As I cannot solve this issue in the library (without unwanted side effects) I propose to close this issue.

The issue - https://github.com/arduino/ArduinoCore-mbed/issues/590 - still stands

**Comment by arotman** [comment] 2022-12-18 12:23
Hi,

Perhaps for now you want to modify your library to call begin(), then end(), then begin() again.
This avoids crash and should have no side-effects.

alan

**Comment by RobTillaart** [comment] 2022-12-18 12:26
Good idea, that should indeed work, side effect is minimal.
If time permits I'll make a PR today

**Comment by RobTillaart** [comment] 2022-12-18 13:39
Created develop branch 
- includes your proposal to add begin()
- moved code from .h to .cpp
- minor edits

Please verify if the develop branch works for you.

**Comment by RobTillaart** [comment] 2022-12-18 14:31
- Quickly checked - https://github.com/arduino/ - AVR, megaAVR, samd and sam cores if adding the extra **begin()** causes memory leaks or other problems. No obvious problems noticed.
- build gave no problems either - https://github.com/RobTillaart/MS5611_SPI/pull/7

**Closed** 2022-12-18 15:27 UTC
Labels: bug

**Comment by RobTillaart** [comment] 2022-12-18 15:29
Merged the PR and released 0.1.2

**Comment by RobTillaart** [comment] 2022-12-21 11:57
@arotman 
FYI, 
https://github.com/arduino/ArduinoCore-mbed/issues/590 is closed and merged 
So in the next release of the mbed it should be in.
